services:
  - type: web
    name: yoga-telegram-bot
    plan: free
    env: docker
    region: frankfurt
    branch: main
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: CHANNEL_ID
        fromSecret: true
      - key: BOT_PATH
        value: "yoga-bot-webhook"
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: yoga-telegram-bot
    healthCheckPath: /health
    # Увеличиваем таймауты
    healthCheckTimeout: 120s
    # Предотвращаем сон сервиса
    autoDeploy: true