name: Java CI (Maven Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean verify

      - name: Package JAR
        run: mvn -B package --file pom.xml

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: yoga-telegram-bot-jar
          path: target/*-jar-with-dependencies.jar
